import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Script from "next/script";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [mapsLoaded, setMapsLoaded] = useState(false);
  useEffect(() => {
    if (!mapsLoaded) return;
    console.log("Maps is loaded");
    // @ts-ignore
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 6,
      center: { lat: 59.893, lng: 10.645 },
    });
  }, [mapsLoaded]);

  return (
    <div className={styles.container}>
      <Script
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_MAPS_API_KEY}&libraries=visualization`}
        onLoad={() => {
          setMapsLoaded(true);
        }}
      />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="map" className={styles.map} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
